version: '3'
services:
  thermos:
    container_name: thermos
    image: ghcr.io/truncj/thermos:latest
    restart: always
    privileged: true
    volumes:
      - ./config:/app/config
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=1
    network_mode: host
  redis:
    container_name: redis
    command: [ "redis-server", "--appendonly", "yes" ]
    image: "redis:alpine"
    restart: always
    volumes:
      - ./redis-data:/data
    network_mode: host

