name: ci

on:
  push:
    branches: main

jobs:
  docker-build-push:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build
        run: docker build -t ghcr.io/${{ github.repository_owner }}/thermos .
      -
        name: Tag
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/thermos ghcr.io/${{ github.repository_owner }}/thermos:latest
          docker tag ghcr.io/${{ github.repository_owner }}/thermos ghcr.io/${{ github.repository_owner }}/thermos:${{ github.sha }}
      -
        name: Push
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/thermos:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/thermos:latest

      -
        name: Deploy
        run: |
          docker-compose pull
          docker-compose up -d
        working-directory: /home/pi/Projects/thermos