name: ci

on:
  push:
    branches: main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm,linux/arm64
      -
        name: Build, Tag and Push
        run: docker buildx build --push --platform=linux/arm64/v8 --tag ghcr.io/${{ github.repository_owner }}/thermos:latest --tag ghcr.io/${{ github.repository_owner }}/thermos:${{ github.sha }} .
      -
        name: Tag
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/thermos ghcr.io/${{ github.repository_owner }}/thermos:latest
          docker tag ghcr.io/${{ github.repository_owner }}/thermos ghcr.io/${{ github.repository_owner }}/thermos:${{ github.sha }}
      -
        name: Push
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/thermos:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/thermos:latest

#      -
#        name: Deploy
#        run: |
#          docker-compose pull
#          docker-compose up -d
#        working-directory: /home/pi/Projects/thermos